# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    env:
      plataform: aws
      region: us-east-1
      account: 123456789012

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Mostrar mensaje"
        run: echo "Hola Mundo Fede mi Angelito"
      
      - name: "Mostrando variables de entorno"
        if: ${{ env.plataform == 'azure' }}
        run: |
          echo "Esto es el valor de plataform: ${{ env.plataform }}"
          echo "Esto es el valor de region: ${{ env.region }}"
          echo "Esto es el valor de account: ${{ env.account }}"

