# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    env:
      plataform: aws
      region: us-east-1
      account: 123456789012
      username: ${{secrets.USERNAME}}
      contrasena: ${{secrets.CONTRASENA}}

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Mostrar mensaje"
        run: echo "Hola Mundo Fede mi Angelito"
      
      - name: "Mostrando variables de entorno"
        # if: ${{ env.plataform == 'azure' }}
        run: |
          echo "Esto es el valor de plataform: ${{ env.plataform }}"
          echo "Esto es el valor de region: ${{ env.region }}"
          echo "Esto es el valor de account: ${{ env.account }}"

          echo "Esto es el valor de username: ${{ env.username }}"
          echo "Esto es el valor de contrasena: ${{ env.contrasena }}"
          echo "Esto es el Project Version: ${{ vars.PROJECT_VERSION }}"          

      - name: "Mostrando valores solo si el usuario es correcto"
        if: ${{ env.username != '' && env.contrasena != '' }}
        run: |
          echo "Si existe usuario y contrasena"

      - name: "Mostrando variables por defecto"
        run: |
          echo "Eventos: ${{toJson(github.event) }}"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"

